version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: symfony_pi_project_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3318:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer:latest
    container_name: symfony_pi_project_adminer
    restart: always
    ports:
      - "40042:8080" # Choose any port in the range 40000-49999

volumes:
  mysql_data:
